export const STORAGES_DIALOG_STATE = 'STORAGES_DIALOG_STATE'

export const STORAGES_LOAD_ALL = 'STORAGES_LOAD_ALL'

export const STORAGES_LOAD_DETAILS_INFO = 'STORAGES_LOAD_DETAILS_INFO'

export const STORAGES_LOAD_REFS = 'STORAGES_LOAD_REFS'

export const STORAGES_LOAD_PRODUTOS = 'STORAGES_LOAD_PRODUTOS'
