export const MACHINES_DIALOG_STATE = 'MACHINES_DIALOG_STATE'

export const MACHINES_LOAD_ALL = 'MACHINES_LOAD_ALL'

export const MACHINES_LOAD_DETAILS_INFO = 'MACHINES_LOAD_DETAILS_INFO'

export const MACHINES_LOAD_REFS = 'MACHINES_LOAD_REFS'

export const MACHINES_LOAD_PRODUTOS = 'MACHINES_LOAD_PRODUTOS'